### ISSUE TITLE
infinitely bootanimation

### ISSUE THREAD

**Issue by asyan4ik** [mt7-dev/android_device_huawei_mt7l09#2]
strangely constantly animation . phone is not visible on adb or lsusb
`asyan4ik@asyan4ik-dev:~/firmware/omnirom_6$ lsusb
Bus 007 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 002 Device 003: ID 1e4e:0103 Cubeternet 
Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 006 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 005 Device 002: ID 093a:2521 Pixart Imaging, Inc. Optical Mouse
Bus 005 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 001 Device 038: ID 18d1:d002 Google Inc. 
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 004 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 003 Device 002: ID 0738:1112 Mad Catz, Inc. 
Bus 003 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
`
`asyan4ik@asyan4ik-dev:~/firmware/omnirom_6$ adb devices
List of devices attached
asyan4ik@asyan4ik-dev:~/firmware/omnirom_6$`
=(

**Comment by gabrielepmattia** [comment]
Which version are you trying to build? Only aosp 6.0.0_r1 is (almost) fully working with this tree

**Comment by asyan4ik** [comment]
i have idea . i need you boot.img from aosp . upload pls

**Comment by gabrielepmattia** [comment]
I uploaded here some working images that I used for cm and aosp https://mega.nz/#F!eV9nxa4L!f6-Sb0TQx4kQQE19GFHAQg
